language: go

go:
  - "1.11.x"

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go get github.com/mattn/goveralls
  - go get github.com/lawrencewoodman/roveralls
  - go get honnef.co/go/tools/cmd/staticcheck

install:
  - dep ensure -vendor-only

script:
  - make build.docker
  - make test
  - roveralls
  - goveralls -v -coverprofile=roveralls.coverprofile -service=travis-ci
