required = [
  "github.com/go-swagger/go-swagger/cmd/swagger",
  "github.com/jteeuwen/go-bindata/go-bindata"
]

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "~1.13.4"

[[constraint]]
  name = "github.com/coreos/container-linux-config-transpiler"
  version = "0.9.0"

[[override]]
  name = "github.com/ajeddeloh/yaml"
  branch = "v2"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/errors"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/runtime"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/strfmt"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/swag"

[[constraint]]
name = "github.com/go-swagger/go-swagger"
version = "~0.16.0"

[[constraint]]
  branch = "master"
  name = "github.com/go-openapi/validate"

[[constraint]]
  branch = "master"
  name = "github.com/jteeuwen/go-bindata"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "0.11.5"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "~2.2.3"

[[constraint]]
  revision = "103fd098999dc9c0c88536f5c9ad2e5da39373ae"
  name = "k8s.io/apimachinery"

[[override]]
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"
  name = "github.com/json-iterator/go"

[[constraint]]
  name = "k8s.io/client-go"
  version = "8.0.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/copystructure"
